@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class Car
interface Command << interface >>
class RemoteControl
class StartCarCommand
class StopCarCommand

StartCarCommand  -[#008200,dashed]-^  Command         
StopCarCommand   -[#008200,dashed]-^  Command         
@enduml
